language: node_js
node_js:
  - "6"
before_script:
  - npm run jshint
  - npm run jscs
  - wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal -v -onlyAutomate -forcelocal $BROWSERSTACK_ACCESS_KEY &
  - sleep 3
  - npm run wdio