language: node_js
node_js:
  - "5"
before_script:
  - npm run jshint
  - npm run jscs
  - npm run mocha
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - java -jar selenium-server-standalone-3.0.0-beta2.jar
script:
  - npm start & npm run wdio