language: node_js
node_js:
  - "6"
before_script:
  - npm run jshint
  - npm run jscs
  - npm run mocha
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - npm start & npm run wdio
